### PR TITLE
Update on getConfig()

### PR DESCRIPTION
**Pull request by Oliv3rDog**
metric = getConfig().isMetric;
must be
metric = getControllerConfig().isMetric;

### CODE REVIEW

**Comment by henrikekblad** [comment]
Could you perhaps update all the examples?

https://github.com/mysensors/MySensorsArduinoExamples/issues/14

**Comment by Oliv3rDog** [comment]
Yes, but I do not have access for that...

**Comment by henrikekblad** [comment]
Sorry, what do you mean by access?  A pull request can contain changes in multiple files.

**Comment by Oliv3rDog** [comment]
I mean I can't change those files.

I get this message when trying:
"You must be on a branch to make or propose changes to this file"

How could I proceed?

**Comment by henrikekblad** [comment]
Fixed in #17

**Pull request closed without merging**
